services:
  iptv-api:
    image: networkio/iptv-api:latest
    container_name: iptv-api
    restart: unless-stopped
    tty: true
    stdin_open: true

    ports:
      - "5180:8080"

    volumes:
      - ./config:/iptv-api/config
      - ./output:/iptv-api/output
      - ./service/app.py:/iptv-api/service/app.py
      - ./static/sports.html:/iptv-api/static/sports.html

    environment:
      PUBLIC_SCHEME: "http"
      PUBLIC_DOMAIN: "192.168.88.113"
      PUBLIC_PORT: "5180"
      NGINX_HTTP_PORT: "8080"
      CDN_URL: ""
      HTTP_PROXY: ""

    networks:
      - iptv-net

  alist:
    image: xhofe/alist:latest
    container_name: alist
    restart: unless-stopped
    volumes:
      - ./data/alist:/opt/alist/data
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
    networks:
      - iptv-net

networks:
  iptv-net:
    driver: bridge