services:
  iptv-api:
    image: guovern/iptv-api:latest
    container_name: iptv-api
    restart: unless-stopped
    tty: true
    stdin_open: true

    ports:
      - "5180:8080"

    volumes:
      - ./config:/iptv-api/config
      - ./output:/iptv-api/output
      - ./service/app.py:/iptv-api/service/app.py
      - ./static/sports.html:/iptv-api/static/sports.html

    environment:
      PUBLIC_SCHEME: "http"
      # Replace with your public domain or IP
      PUBLIC_DOMAIN: "192.168.88.113"
      PUBLIC_PORT: "5180"
      NGINX_HTTP_PORT: "8080"
      CDN_URL: ""
      HTTP_PROXY: ""