#!/usr/bin/env bash
set -euo pipefail

# gen-nginx-routes.sh — 从 tools.json 自动生成 nginx 静态工具路由
# 读取 user_output/tools.json 中 type=static 的条目，生成 location 块
# 输出到 stdout，可重定向到 tools-routes.conf

PROJ_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TOOLS_JSON="$PROJ_DIR/user_output/tools.json"
OUTPUT="$PROJ_DIR/tools-routes.conf"

python3 -c "
import json

with open('$TOOLS_JSON') as f:
    tools = json.load(f)

lines = []
for t in tools:
    if t.get('type') != 'static':
        continue
    href = t['href'].rstrip('/')
    lines.append(f'location {href}/ {{')
    lines.append(f'    root /iptv-api/user_output;')
    lines.append(f'}}')
    lines.append('')

if not lines:
    lines = ['# (no static tools)\n']

with open('$OUTPUT', 'w') as f:
    f.write('# Auto-generated by gen-nginx-routes.sh — DO NOT EDIT\n')
    f.write('# Run: scripts/gen-nginx-routes.sh\n\n')
    f.write('\n'.join(lines))

print(f'✓ Generated {len([l for l in lines if l.startswith(\"location\")])} routes → $OUTPUT')
"
